### ISSUE TITLE
Ore Dictionary Export Bus crashes the game

### ISSUE THREAD

**Issue by KleinGrrmpf** [ExtraCells/ExtraCells2#676]
When I place an Ore Dictionary Export Bus and it tries to connect to the system, it crashes the game. After a restart of the game, the bus is connected to the system and works, though. It also sometimes crashes the game when trying to pull items out of the system. Every of these crashes comes with the same reason: Description: 
Ticking GridNode
java.lang.IllegalArgumentException: Stack can not be invalid!

I'm on the latest version of the mod (2.6.4) playing FTB Revelation to which I've added the extended crafting mod, although I think that this is not a mod conflict.
[crash-on-place-server.txt](https://github.com/ExtraCells/ExtraCells2/files/3810342/crash-on-place-server.txt)
[crash-while-exporting-server.txt](https://github.com/ExtraCells/ExtraCells2/files/3810344/crash-while-exporting-server.txt)

**Comment by KleinGrrmpf** [comment]
Now it crashes every time I load up the game. I configured the Export Bus like so:
@"biomesoplenty" & tree* | flower*
Without the quotation marks ;)

**Comment by HeyZeer0** [comment]
bump, same issue here!

Used Versions:
```
Minecraft: 1.12.2
SpongeAPI: 7.1.0-2ad94d34
Sponge: 1.12.2-7.1.7-SNAPSHOT
SpongeForge: 1.12.2-2838-7.1.7-RC3946
Minecraft Forge: 14.23.5.2847
JVM: 1.8.0_212/64-bit (Oracle Corporation)
OS: Linux (4.15.0-64-generic/amd64)
```

Crash Report: 
https://pastebin.com/wtDLSETK

**Comment by KleinGrrmpf** [comment]
When you go back to one of the stable versions, you can enter the world again

**Comment by HeyZeer0** [comment]
@KleinGrrmpf I made a quickfix using Mixin to avoid the execution of the ``doWork`` method, it will work for the time the dev fix this issue

**Comment by ruifung** [comment]
Well, that was unexpected, I did test it a fair amount prior to posting the update.

**Comment by ruifung** [comment]
Can anyone try it with this version and see if it fixes the issue. It should, as I really wasn't expecting it to be getting empty itemstacks. As for the other one... I never managed to reproduce it though,

[ExtraCells-1.12.2-2.6.5.NIGHTLY.zip](https://github.com/ExtraCells/ExtraCells2/files/3830220/ExtraCells-1.12.2-2.6.5.NIGHTLY.zip)

**Comment by KleinGrrmpf** [comment]
No crash so far, and I had the system export items. Guess you fixed it. Thanks :)

**Comment by LemADEC** [comment]
Fix is effective in single player, can we get it released?

**Comment by LemADEC** [comment]
@ruifung any chance we get that fix released on CurseForge?

**Comment by ruifung** [comment]
Sorry, I've been busy IRL. I'll release it on curseforge soon.

**Comment by jk1895** [comment]
Game is still crashing. :(
[crash-2019-12-16_17.14.24-server.txt](https://github.com/ExtraCells/ExtraCells2/files/3969107/crash-2019-12-16_17.14.24-server.txt)

**Comment by ruifung** [comment]
Closed in 8ae42f39e43d3060e23de6e6d4115374a61cdb06

Should've been released last month, but work IRL got busy and I forgot about it.

Also released to curseforge.
